# Generated by Django 5.0.1 on 2024-02-08 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_publication_users_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='likes_count',
        ),
    ]
